spring:
  application:
    name: mall-search
  zipkin:
    base-url: http://120.48.67.55:9411 # zipkin服务地址
    sender:
      type: web # 数据收集方式：web、kafka、rabbit，我使用的是最简单的web，别的方式请自行学习
    discovery-client-enabled: false #关闭服务发现 否则springcloud会把zipkin的url当作服务名称
  sleuth:
    redis:
      enabled: false  # 关闭redis链路追踪，否则会产生死锁，这是官方的一个BUG
    sampler:
      probability: 1 # sleuth 日志记录采样率，1为100%，默认为0.1即10%，正式环境视情况修改该配置。
  redis:
    password: L200107208017@./
    cluster:
      max-redirects: 3
      nodes: 124.222.22.217:6379,124.223.99.166:6379,124.221.154.235:6379
#    sentinel:
#      master: mymaster
#      nodes:
#        - 124.222.22.217:26379
#        - 124.223.99.166:26379
#        - 124.221.154.235:26379
#      password: L200107208017@./
  session:
    store-type: redis

elasticsearch:
  host: 120.48.78.44
  port: 9200
  username: elastic
  password: L200107208017./@


server:
  port: 16006