spring:
  application:
    name: mall-order
  zipkin:
    base-url: http://120.48.67.55:9411 # zipkin服务地址
    sender:
      type: web # 数据收集方式：web、kafka、rabbit，我使用的是最简单的web，别的方式请自行学习
    discovery-client-enabled: false #关闭服务发现 否则springcloud会把zipkin的url当作服务名称
  sleuth:
    redis:
      enabled: false  # 关闭redis链路追踪，否则会产生死锁，这是官方的一个BUG
    sampler:
      probability: 1 # sleuth 日志记录采样率，1为100%，默认为0.1即10%，正式环境视情况修改该配置。
  datasource:
    hikari:
      max-lifetime: 90000 # 180000  # 默认 180000ms 30min ，与数据库端保持一致
    url: jdbc:mysql://120.48.67.55:8066/mall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: L200107208017./@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    data-format: yyyy-MM-dd HH:mm:ss
  #    alibaba:
  #      seata:
  #        tx-service-group: tx_group

  jackson:
    date-format: yyyy年MM月dd日 HH时mm分ss秒
    time-zone: Asia/Shanghai

  rabbitmq:
    host: 120.48.67.55
    port: 5672
    virtual-host: /prod
    username: june
    password: L200107208017./@
    publisher-returns: true  # 消息到达队列确认
    template:
      mandatory: true   # 消息只要抵达队列，就以异步方式优先回调这个 returnconfirm
    listener:
      simple:
        acknowledge-mode: manual

  redis:
    password: L200107208017@./
    cluster:
      max-redirects: 3
      nodes: 124.222.22.217:6379,124.223.99.166:6379,124.221.154.235:6379
#    sentinel:
#      master: mymaster
#      nodes:
#        - 124.222.22.217:26379
#        - 124.223.99.166:26379
#        - 124.221.154.235:26379
#      password: L200107208017@./

  session:
    store-type: redis


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto


server:
  port: 16004

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 100000


mall:
  thread:
    core-size: 10
    max-size: 200
    keep-alive-time: 5

alipay:
  app_id: 2021000117663691
  notify_url: http://order.projectdemo.top/order/alipay/notify
  return_url: http://member.projectdemo.top/memberOrder.html
  sign_type: RSA2
  charset: utf-8

